includes:
- configs/datasets/hateful_memes/bert.yaml

model_config:
  concat_bert:
    num_labels: 22
    classifier:
      type: mlp
      params:
        num_layers: 2
    losses:
    - type: logit_bce

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

optimizer:
  type: adam_w
  params:
    lr: 1e-5
    eps: 1e-8

evaluation:
  metrics:
  - multilabel_micro_f1
  - multilabel_macro_f1

training:
  batch_size: 16
  lr_scheduler: true
  max_updates: 18000
  early_stop:
    criteria: hateful_memes/roc_auc
    minimize: false

checkpoint:
  pretrained_state_mapping:
    base: base
